package middleware

import (
	"ClaranCloudDisk/util"
	"net/http"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"golang.org/x/time/rate"
)

type Security struct {
	maxRequestsEveryMinute int
}

func NewSecurity(maxRequestsEveryMinute int) *Security {
	return &Security{maxRequestsEveryMinute: maxRequestsEveryMinute}
}

// UserRateLimitMiddleware 用户级限流
func (s *Security) UserRateLimitMiddleware() gin.HandlerFunc {
	var (
		buckets = make(map[string]*util.TokenBucket)
		mu      sync.Mutex
	)

	return func(c *gin.Context) {
		// 获取用户IP
		userIP := c.ClientIP()

		// 令牌桶
		mu.Lock()
		bucket, ok := buckets[userIP]
		// 如果没有令牌桶，创建令牌桶
		if !ok {
			bucket = util.NewTokenBucket(50, 1)
			buckets[userIP] = bucket
		}
		mu.Unlock()

		// 令牌检查
		if !bucket.Allow() {
			zap.S().Errorf("请求过于频繁，请稍候再试")
			util.Error(c, http.StatusTooManyRequests, "请求过于频繁，请稍候再试")
			c.Abort()
			return
		}

		c.Next()
	}
}

// RateLimitedMiddleware 全局限流
func (s *Security) RateLimitedMiddleware() gin.HandlerFunc {
	maxRequestsEveryMinute := s.maxRequestsEveryMinute

	limiter := rate.NewLimiter(rate.Every(time.Minute/time.Duration(maxRequestsEveryMinute)), maxRequestsEveryMinute)

	return func(c *gin.Context) {
		if !limiter.Allow() {
			zap.S().Errorf("请求过于频繁")
			util.Error(c, http.StatusTooManyRequests, "请求过于频繁，请稍候再试")
			c.Abort()
			return
		}
		c.Next()
	}
}

// SecurityMiddleware generated by Deepseek
func (s *Security) SecurityMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		// 防止点击劫持
		c.Header("X-Frame-Options", "DENY")

		// 防止MIME类型嗅探
		c.Header("X-Content-Type-Options", "nosniff")

		// 启用XSS过滤
		c.Header("X-XSS-Protection", "1; mode=block")

		// Content Security Policy
		c.Header("Content-Security-Policy",
			"default-src 'self'; "+
				"script-src 'self' 'unsafe-inline' 'unsafe-eval'; "+
				"style-src 'self' 'unsafe-inline'; "+
				"img-src 'self' data: https:; "+
				"font-src 'self'; "+
				"connect-src 'self'; "+
				"frame-ancestors 'none';")

		// Referrer Policy
		c.Header("Referrer-Policy", "strict-origin-when-cross-origin")

		// Permissions Policy
		c.Header("Permissions-Policy",
			"geolocation=(), microphone=(), camera=()")

		c.Next()
	}
}
