package middleware

import (
	"ClaranCloudDisk/util"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"golang.org/x/time/rate"
)

type Security struct {
	maxRequestsEveryMinute int
}

func NewSecurity(maxRequestsEveryMinute int) *Security {
	return &Security{maxRequestsEveryMinute: maxRequestsEveryMinute}
}

func (s *Security) RateLimitedMiddleware() gin.HandlerFunc {
	maxRequestsEveryMinute := s.maxRequestsEveryMinute

	limiter := rate.NewLimiter(rate.Every(time.Minute/time.Duration(maxRequestsEveryMinute)), maxRequestsEveryMinute)

	return func(c *gin.Context) {
		if !limiter.Allow() {
			zap.S().Errorf("请求过于频繁")
			util.Error(c, http.StatusTooManyRequests, "请求过于频繁，请稍候再试")
			c.Abort()
			return
		}
		c.Next()
	}
}

// SecurityMiddleware generated by Deepseek
func (s *Security) SecurityMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		// 防止点击劫持
		c.Header("X-Frame-Options", "DENY")

		// 防止MIME类型嗅探
		c.Header("X-Content-Type-Options", "nosniff")

		// 启用XSS过滤
		c.Header("X-XSS-Protection", "1; mode=block")

		// Content Security Policy
		c.Header("Content-Security-Policy",
			"default-src 'self'; "+
				"script-src 'self' 'unsafe-inline' 'unsafe-eval'; "+
				"style-src 'self' 'unsafe-inline'; "+
				"img-src 'self' data: https:; "+
				"font-src 'self'; "+
				"connect-src 'self'; "+
				"frame-ancestors 'none';")

		// Referrer Policy
		c.Header("Referrer-Policy", "strict-origin-when-cross-origin")

		// Permissions Policy
		c.Header("Permissions-Policy",
			"geolocation=(), microphone=(), camera=()")

		c.Next()
	}
}
